name: FrontEnd CI Pipeline

on:
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    if: contains(github.event.pull_request.labels.*.name, '🎨 Front-end')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # - name: Run Frontend tests
      #   run: npm run test -w=frontend

      - name: Build Frontend
        run: npm run build -w=frontend
